### ISSUE TITLE
How to use existing Express/Koa middlewares with typera?

### ISSUE THREAD

**Issue by akheron** [akheron/typera#11]
Document this, maybe add some helper functions

**Comment by frabbit** [comment]
hi @akheron, does an example for this exist somewhere? I'm interested in using existing koa middleware with typera-koa.

**Comment by akheron** [comment]
The easiest way would be to just `app.use` the middleware outside typera.

If you want to add route-level middleware along with typera middleware, unfortunately no ready-made solution exists yet for arbitrary middleware.

**Comment by frabbit** [comment]
@akheron thx, yes i need route-level middleware for keycloak permission checks. Will try to figure out how it works. There is not even an official keycloak middleware for koa, so i have to adapt twice :smiley: .

**Comment by frabbit** [comment]
Let me know if you have an Example for any koa middleware, this would already help.

**Comment by akheron** [comment]
Arbitrary express middleware can now be used with `typera-express` using the `Middleware.wrapNative` helper. `typera-koa` would need a similar helper.
