### ISSUE TITLE
Add support for response.render

### ISSUE THREAD

**Issue by marcmartino** [akheron/typera#145]
I can't seem to find it if it exists, but support for response.render would allow html responses easily out of the box. If the ability to use templating engines with typera exists then i suppose this issue would be that there should be something in the README about how it would be done (or html responses in general).

**Comment by akheron** [comment]
There’s no builtin support for rendering engines, and no intention to add it either. You can render the html with the engine of your choice and return `Response.ok(html, { 'Content-Type': 'text/html' })`.
