### ISSUE TITLE
Non JSON body parser

### ISSUE THREAD

**Issue by AlexGalays** [akheron/typera#191]
Hello! Thank you for the good work. It makes coding with express almost pleasant :D  (its middleware system is still crazily untyped but it's now manageable)

Am I correct to assume the scope of this lib so far is to provide a parser only for JSON based bodies? Do you have any plan to add parsing for multipart, binary, etc? If nope, perhaps you can add some pointers in the documentation as to how to quickly plug an express middleware to parse a file, etc? Perhaps that could be a real life example of how to use https://github.com/akheron/typera#using-express-middleware ?

Cheers

**Comment by grizio** [comment]
I think this lib is not to provide a parser for JSON based body. You need to add your own json body parser:

> Note: You must use a Express or Koa body parsing middleware for Parser.body to work.
> — https://github.com/akheron/typera#parserbodytcodec-ttypet-middleware-body-t--responsebadrequeststring

You can add any body parser in the system (json, form-data, custom):

```
express()
  .use(jsonBodyParserMiddleware) // body parser for content-type = application/json
  .use(formDataBodyParserMiddleware) // body parser for content-type = multipart/form-data
  .use(router(
    // Route with application/json
    route.post('/create')
      .use(Parser.body(t.type({ action: t.string }))),

    // Route with multipart/form-data
    route.post('/upload')
      .use(Parser.body(t.type({
        filename: t.string, // A value got from a text field
        file: myCustomFileType // The temporary file info of type { path: string, size: number, … }
      })))
  ).handler())
```

**Comment by akheron** [comment]
Correct. `typera-express` just takes the value in `req.body` and applies the io-ts codec to it.

**Comment by dev-m1-macbook** [comment]
BYO body-parser is understandable, and it's what a lot of libs actually do.

But from ergonomics perspective, wouldn't custom-body-parser help in providing request-body types for typera-openapi?

eg). 
```typescript
route
  .useBodyParser(Parser.json) // --> "application/json"
  .useBodyParser(Parser.formDataNoFiles) // --> "application/x-www-form-urlencoded"
  .useBodyParser(Parser.formDataWithFiles) // --> "multipart/form-data"
 ```
