### ISSUE TITLE
Wildcard/fallback route

### ISSUE THREAD

**Issue by Giesch** [akheron/typera#223]
Hi! Thanks for this library, it's wonderful. 
This is either a support question or a feature request, not really an issue. Let me know if there's a better place to ask than this.

Is there a way in typera to add a wildcard route that matches any unmatched path? Or in lieu of that, an 'official' way to customize the 404 response? The use case is an app serving html, where I'd like to serve a top-level 404 page. I'm already using a middleware to wrap the html responses, and can see how to do this by setting a flag there. But I'd rather use an 'official' way to do it, if there is one, and avoid mutating the response.

**Comment by akheron** [comment]
I’m afraid this is a case where you have to rely on express or koa features.
