### ISSUE TITLE
Migrate to @koa/router?

### ISSUE THREAD

**Issue by njgingrich** [akheron/typera#24]
Hey! This project seems pretty neat and I've started using it, but I had to alias `@koa/router` to `koa-router` in my project because `typera-koa` has a devDependency of koa-router, which (to the best of my knowledge) is now unmaintained and was forked to https://github.com/koajs/router.

I haven't had any issues with that rename, so I think `@koa/router` should be a drop-in replacement for `koa-router` in this package.

**Comment by akheron** [comment]
Fixed and released v0.7.3. Thanks for reporting!
