### ISSUE TITLE
Separate `handler` from route declaration

### ISSUE THREAD

**Issue by ajmnz** [akheron/typera#246]
Hey, thanks for the lib!

I was wondering how to handle a particular case with typera.

In regular Express I usually separate routes and controllers into separate files and do something like the following:

```ts
// authRoutes.ts

const router = express.Router();

router.post("/login", authController.login);

// authController.ts

const login: express.RequestHandler = (req, res, next) => {
  // Handle
}
```

But with this lib it seems like `route.post()` doesn't return the route, which makes it impossible to do something like:

```ts
// authRoutes.ts

import { route } from "typera-express";

export const loginRoute = route.post("/auth/login");

// authController.ts

import { loginRoute } from "../routes/authRoutes";

const loginController = loginRoute.handler((request) => {
  // Handle
})

```

Is there any way to achieve this? Even if it's another completely different method. The goal is to separate the route handling logic from the route declaration.

Thanks!

**Comment by akheron** [comment]
What you're suggesting is not directly possible, because the handler function's type tells the type system which are the possible responses for the route.

You could do it like this instead:

```
// authController.ts

export async function loginController(username: string, password: string): Promise<boolean> {
  // ...
  return true
}

// authRoutes.ts

import { loginController } from "../controllers/loginController"

export const loginRoute = route.post("/auth/login").handler((req) => 
  loginController(req.body.username, req.body.password)
    .then(success => success ? Response.ok() : Response.badRequest())
```

You could also return the response directly from the controller if you want.
