### ISSUE TITLE
The middleware finalizer will not be called if value is falsy

### ISSUE THREAD

**Issue by wolfie** [akheron/typera#25]
I have a middleware that times requests in a rough manner: 

```typescript
export const perfLogger: Middleware.Middleware<unknown, never> = ({ req }) => {
  const start = Date.now();
  const authorizedUser = getAuthorizedUserIfExists(req);
  const path = req.path;
  return Middleware.next(undefined, () =>
    logTimeToDatabase({
      start,
      authorizedUser,
      path
    })
  );
};
```

The finaliser will never get called, as the code in Typera checks whether the returned value weakly evaluates to `null` (`packages/typera-common/src/middleware.ts#L30`: `if (value == null) return {}`)

My middleware is not interested in providing any results to the main request object, but one workaround would be to provide a nonsense value that does not weakly evaluate to `null`

**Comment by akheron** [comment]
Try returning `{}`

**Comment by akheron** [comment]
The ultimate fix for this would be to add a new function, maybe`Middleware.finalizeOnly()`, and use that to return from middleware that don’t add a value but only want to have a finalizer.

**Comment by akheron** [comment]
Decided to allow adding just the finalizer by using  `undefined` or `{}` with `Middleware.next()`, and documenting this.
